### ISSUE TITLE
How do I setup the 'Dark+' theme as the Night Theme?

### ISSUE THREAD

**Issue by yatiac** [timrodz/vscode-light-switch#23]
Title pretty much says it all.

**Comment by timrodz** [comment]
Hey @yatiac, I just started testing this and you seem to have encountered the first bug! 

**FIX**: The `lightSwitch.nightTheme` property must be set to `"Default Dark+"` (instead of `"Dark+"`).

![image](https://user-images.githubusercontent.com/7434353/74986996-14940680-549f-11ea-947f-af6f9c6e6a14.png)

Here's the explanation to why it must be done this way:

When you set a theme on VS Code, it will override the `"workbench.colorTheme"` property of your workspace's `settings.json` file. I set my theme to be **Abyss**, here's how the change will look:

```json
"workbench.colorTheme": "Abyss"
```

However, when specifying your theme as **Dark+**, the `"workbench.colorTheme"` property is hidden/removed. This is because **Dark+** is the default native VS Code theme.

With further investigation, I decided to inspect the contents of `defaultSettings.json` - This is where the problem was. I noticed the `"workbench.colorTheme"` property is actually stored as:

```json
"workbench.colorTheme": "Default Dark+"
```

And there you have it. VS Code is showing the theme's name as **Dark+**, when in reality it's called **Default Dark+**.

Hope this helps!
